---
# Publicly visible infrastructure variables
ansible_user: ansible

# Infrastructure State
infra_state: "{{ state | default('present') }}"

# Scaling & Naming
guest_count: 1
vm_count: "{{ guest_count | int }}"
vm_group_prefix: "{{ group_prefix | default('ubuntu-web') }}"
vm_name_prefix: "{{ name_prefix | default('ubuntu-web') }}"

# Templates & Images
base_image_source: "{{ vm_image | default('/data/sdc1_vol1/iso/ubuntu-24.04-minimal-cloudimg-amd64.img') }}"
vm_template: "{{ spec_template | default('vm_spec.xml.j2') }}"

# Paths & URI
image_path: "/var/lib/libvirt/images"
libvirt_uri: "qemu:///system"

# Add ssh public key here to add it to the provisioned VMs
ssh_public_key: ""